import './App.css'
import Home from './pages/Home'

function App() {

  return (
      <>
          <Home />
      </>
  )
}



//TO DO LIST

//CLEAR ALL THE SKILLS
//ONLY ALLOW INSERTION OF SKILLS AVAILABLE IN THE DB
//RESEARCH DIRECTLY YOUR JOB

//FOR THE FUTURE:
//PREDICT, BASED ON THE SKILLS, HOW MUCH IS YOUR JOB LIKELY TO BE REPLACED BY AI
//E.G. ANY PROGRAMMING LANGUAGE MAY LIFT THE INDEX OF REPLACEMENT, WHILE ANY CRUCIAL
//SOFT SKILL MAY LOWER IT.

export default App